# Generated by Django 4.2.3 on 2023-08-30 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
